dict = {}

name = input("Enter friends Name : ")
lang = input("Enter Language name : ")
dict.update({name : lang})
name = input("Enter friends Name : ")
lang = input("Enter Language name : ")
dict.update({name : lang})
name = input("Enter friends Name : ")
lang = input("Enter Language name : ")
dict.update({name : lang})
name = input("Enter friends Name : ")
lang = input("Enter Language name : ")
dict.update({name : lang})
print(dict)